// NEXA COPY SYSTEM — LOCKED VOICE
// ────────────────────────────────────────────────────────────────────────────
// ENGLISH: Confident, minimal, direct. No fluff. Like a smart operator.
// ARABIC:  خليجي أصيل — مكتوب بعقلية عربية لا بترجمة.
//          الأسلوب: دافئ، واثق، مباشر. مثل صاحب يعرف شغله.
//          مرجع الأسلوب: tabby.ai/ar-AE — خليجي يمشي، راقٍ يكفي، حميمي يكفي.
//          قاعدة ذهبية: لو بدّت مترجمة، أعد كتابتها من الصفر.
// Nexa = اسم لاتيني، يُبقى كما هو دائماً — لا يُترجم أبداً
// الخط: Tajawal — https://fonts.google.com/share?selection.family=Tajawal:wght@200;300;400;500;700;800;900
// ────────────────────────────────────────────────────────────────────────────

export type Lang = 'en' | 'ar'

export const AR_FONT = "'Tajawal', system-ui, sans-serif"

// ── NAVIGATION ──────────────────────────────────────────────────────────────
export const nav = {
  en: {
    dashboard:    'Dashboard',
    brandBrain:   'Brand Brain',
    insights:     'Insights',
    strategy:     'Strategy',
    automate:     'Automate',
    studio:       'Studio',
    schedule:     'Schedule',
    amplify:      'Amplify',
    integrations: 'Integrations',
    agency:       'Agency',
    leadPage:     'Lead page',
    settings:     'Settings',
    upgrade:      'Upgrade',
    logout:       'Log out',
  },
  ar: {
    dashboard:    'الرئيسية',
    brandBrain:   'Brand Brain',
    insights:     'الإنسايتس',
    strategy:     'الاستراتيجية',
    automate:     'الأتمتة',
    studio:       'الاستوديو',
    schedule:     'الجدول',
    amplify:      'Amplify',
    integrations: 'الاتصالات',
    agency:       'الوكالة',
    leadPage:     'صفحة العملاء',
    settings:     'الإعدادات',
    upgrade:      'طوّر خطتك',
    logout:       'تسجيل الخروج',
  },
}

// ── DASHBOARD ────────────────────────────────────────────────────────────────
export const dashboard = {
  en: {
    greetingMorning:    'Good morning',
    greetingDay:        'Good afternoon',
    greetingEvening:    'Good evening',
    commandCenter:      'command center',
    brandReady:         'Your brand is ready. What are we building today?',
    brainNotTrained:    "Nexa hasn't learned your brand yet.",
    uploadToStart:      'Give her what she needs — then watch.',
    readingSignals:     'Nexa is reading your brand...',
    stat_credits:       'Credits',
    stat_built:         'Built',
    stat_published:     'published',
    stat_scheduled:     'Scheduled',
    stat_upcoming:      'upcoming',
    stat_streak:        'Streak',
    stat_keepItUp:      'keep it up',
    stat_startOne:      'start one',
    stat_voiceScore:    'Voice Score',
    stat_onBrand:       'on brand',
    stat_good:          'good',
    stat_trainBrain:    'train Nexa',
    todaysPriority:     "Today's Priority",
    writeThisToday:     'Write This Today',
    bestOn:             'Best on ',
    oneThing:           'One Thing',
    voiceDrift:         'Voice Drift Detected',
    recalibrate:        'Recalibrate',
    agents_title:       'Agents',
    agents_sub:         'One click. Nexa executes.',
    agents_viewAll:     'View all ',
    agents_lastRun:     'Last run ',
    agents_run:         'Run',
    agents_running:     'Running',
    agents_completed:   'completed',
    agents_openStudio:  'Open Studio →',
    queue_title:        'Queue',
    queue_scheduled:    'posts scheduled',
    queue_clear:        'Queue is clear',
    queue_manage:       'Manage →',
    queue_nothing:      'Nothing queued yet',
    queue_scheduleHint: 'Schedule your first post to see it here',
    queue_createPost:   'Create a post →',
    qa_write:           'Write content',
    qa_strategy:        'Build strategy',
    qa_schedule:        'Schedule',
    qa_brand:           'Brand Brain',
    qa_studio:          'Studio',
    qa_stratSub:        'Strategy',
    qa_calSub:          'Calendar',
    qa_intelSub:        'Intelligence',
    activity_title:     'Activity',
    activity_sub:       'Everything happening in real time',
    activity_ago:       ' ago',
    activity_empty:     'No activity yet',
    activity_hint:      'Every generation and publish appears here',
    bi_title:           'Brand Intelligence',
    bi_active:          'Active — learning from every generation',
    bi_notTrained:      'Not yet trained',
    bi_activeLabel:     'Active',
    bi_checkDrift:      'Check drift',
    bi_voiceMatch:      'Voice match',
    bi_audienceFit:     'Audience fit',
    bi_visualStyle:     'Visual style',
    bi_learned:         'What Nexa has learned',
    bi_nexaInsight:     "Nexa's Insight",
    bi_brainEmpty:      "Brand Brain isn't trained yet",
    bi_uploadHint:      'Upload your brand assets and Nexa learns your voice, style, and audience',
    bi_train:           'Train Brand Brain →',
    loading:            'Loading your workspace',
  },
  ar: {
    greetingMorning:    'صباح الخير',
    greetingDay:        'يعطيك العافية',
    greetingEvening:    'مساء الخير',
    commandCenter:      'لوحة القيادة',
    brandReady:         'براندك جاهز. ايش نبني اليوم؟',
    brainNotTrained:    '.Nexa ما تعلّمت براندك بعد',
    uploadToStart:      'أعطها اللي تحتاجه — وشوف النتيجة.',
    readingSignals:     '...Nexa تقرأ براندك',
    stat_credits:       'الرصيد',
    stat_built:         'مُنجز',
    stat_published:     'منشور',
    stat_scheduled:     'مجدوَل',
    stat_upcoming:      'قادم',
    stat_streak:        'تسلسل',
    stat_keepItUp:      'واصل',
    stat_startOne:      'ابدأ',
    stat_voiceScore:    'نبرة البراند',
    stat_onBrand:       'على النبرة',
    stat_good:          'ممتاز',
    stat_trainBrain:    'درّب Nexa',
    todaysPriority:     'أولوية اليوم',
    writeThisToday:     'اكتب هذا اليوم',
    bestOn:             'الأفضل على ',
    oneThing:           'شيء واحد',
    voiceDrift:         'انزياح في نبرة البراند',
    recalibrate:        'أعد المعايرة',
    agents_title:       'الوكلاء',
    agents_sub:         '.نقرة وحدة. Nexa تنفّذ',
    agents_viewAll:     'شوف الكل ←',
    agents_lastRun:     'آخر تشغيل ',
    agents_run:         'شغّل',
    agents_running:     'شغّال...',
    agents_completed:   'اكتمل',
    agents_openStudio:  'افتح الاستوديو ←',
    queue_title:        'القائمة',
    queue_scheduled:    'منشور مجدوَل',
    queue_clear:        'ما في شيء مجدوَل',
    queue_manage:       'إدارة ←',
    queue_nothing:      'القائمة فاضية لحسابها',
    queue_scheduleHint: 'جدوِل أول منشور وشوفه هنا',
    queue_createPost:   'اصنع منشور ←',
    qa_write:           'كتابة محتوى',
    qa_strategy:        'بناء استراتيجية',
    qa_schedule:        'جدولة',
    qa_brand:           'Brand Brain',
    qa_studio:          'الاستوديو',
    qa_stratSub:        'استراتيجية',
    qa_calSub:          'تقويم',
    qa_intelSub:        'ذكاء',
    activity_title:     'النشاط',
    activity_sub:       'كل شيء يصير في الوقت الفعلي',
    activity_ago:       ' مضت',
    activity_empty:     'ما في نشاط بعد',
    activity_hint:      'كل إنشاء ونشر يظهر هنا',
    bi_title:           'ذكاء البراند',
    bi_active:          'نشط — يتعلم من كل إنشاء',
    bi_notTrained:      'ما تدرّب بعد',
    bi_activeLabel:     'نشط',
    bi_checkDrift:      'تحقق من الانزياح',
    bi_voiceMatch:      'تطابق النبرة',
    bi_audienceFit:     'ملاءمة الجمهور',
    bi_visualStyle:     'الأسلوب البصري',
    bi_learned:         'ايش تعلّمت Nexa',
    bi_nexaInsight:     'رأي Nexa',
    bi_brainEmpty:      'Brand Brain ما اتدرّب بعد',
    bi_uploadHint:      'ارفع ملفات براندك وراح تتعلم Nexa نبرتك وأسلوبك وجمهورك',
    bi_train:           'درّب Brand Brain ←',
    loading:            '...Nexa تحمّل مساحة عملك',
  },
}

// ── BRAND BRAIN ──────────────────────────────────────────────────────────────
export const brandBrain = {
  en: {
    heading:          'Brand Brain',
    subheading:       "Your brand's intelligence layer.",
    upload_label:     'Drop your brand assets here',
    upload_sub:       'Logos, decks, guidelines, copy — anything that defines you.',
    upload_btn:       'Upload files',
    upload_or:        'or drag and drop',
    analyzing:        'Reading between the lines...',
    analyzing_sub:    'This takes a moment. Good things do.',
    score_label:      'Brand clarity score',
    score_sub:        'Based on consistency, voice, and positioning.',
    insights_label:   'What we found',
    recs_label:       'What to sharpen',
    voice_label:      'Your brand voice',
    positioning:      'Positioning',
    personality:      'Personality',
    audience:         'Audience',
    chat_placeholder: 'Ask anything about your brand...',
    chat_hint:        'Try: "What does my brand sound like?" or "Where am I inconsistent?"',
    empty_state:      'Upload your brand assets to begin.',
    empty_sub:        'The more you share, the sharper the picture.',
    reanalyze:        'Re-analyze',
    export:           'Export report',
  },
  ar: {
    heading:          'Brand Brain',
    subheading:       '.الطبقة الذكية لبراندك',
    upload_label:     'أسقط ملفات براندك هنا',
    upload_sub:       'شعارات، عروض، إرشادات، نصوص — كل ما يُعرّفك.',
    upload_btn:       'ارفع الملفات',
    upload_or:        'أو اسحب وأسقط',
    analyzing:        '...Nexa تقرأ بين السطور',
    analyzing_sub:    '.هذا يأخذ لحظة. الأشياء الجيدة تستحق الانتظار',
    score_label:      'وضوح البراند',
    score_sub:        '.بناءً على الاتساق والنبرة والتموضع',
    insights_label:   'ايش لقيناه',
    recs_label:       'ايش يحتاج صقل',
    voice_label:      'صوت براندك',
    positioning:      'التموضع',
    personality:      'الشخصية',
    audience:         'الجمهور',
    chat_placeholder: '...اسأل Nexa أي شيء عن براندك',
    chat_hint:        '"كيف يبدو براندي؟" أو "وين مو متسق؟" :جرّب',
    empty_state:      '.ارفع ملفات براندك للبدء',
    empty_sub:        '.كلما شاركت أكثر، كانت الصورة أوضح',
    reanalyze:        'حلّل من جديد',
    export:           'صدّر التقرير',
  },
}

// ── INSIGHTS ─────────────────────────────────────────────────────────────────
export const insights = {
  en: {
    heading:        'Insights',
    subheading:     "What your brand is telling you — if you listen.",
    empty:          'No insights yet.',
    empty_sub:      'Run Brand Brain first. Then come back here.',
    filter_all:     'All',
    filter_voice:   'Voice',
    filter_market:  'Market',
    filter_content: 'Content',
    filter_growth:  'Growth',
    new_label:      'New',
    unlock_label:   'Unlock insight',
    locked_hint:    'Upgrade to unlock deeper insights.',
    trend_up:       'Trending up',
    trend_down:     'Needs attention',
    trend_neutral:  'Stable',
    ask_more:       'Explore this insight',
    summary:        'The big picture',
    loading:        'Surfacing insights...',
  },
  ar: {
    heading:        'الإنسايتس',
    subheading:     '.ما يقوله براندك — لو أنصتّ',
    empty:          '.ما في إنسايتس بعد',
    empty_sub:      '.شغّل Brand Brain أولاً. ثم ارجع هنا',
    filter_all:     'الكل',
    filter_voice:   'النبرة',
    filter_market:  'السوق',
    filter_content: 'المحتوى',
    filter_growth:  'النمو',
    new_label:      'جديد',
    unlock_label:   'افتح الإنسايت',
    locked_hint:    '.طوّر خطتك لتفتح إنسايتس أعمق',
    trend_up:       'في ارتفاع',
    trend_down:     'يحتاج اهتمام',
    trend_neutral:  'مستقر',
    ask_more:       'استكشف هذا الإنسايت',
    summary:        'الصورة الكبيرة',
    loading:        '...Nexa تستخرج الإنسايتس',
  },
}

// ── STRATEGY ─────────────────────────────────────────────────────────────────
export const strategy = {
  en: {
    heading:         'Strategy',
    subheading:      'Your strategy, built with precision. Not speed.',
    new_btn:         'Build new strategy',
    template_label:  'Start from a template',
    custom_label:    'Build from scratch',
    goal_label:      'What do you want to achieve?',
    goal_hint:       'Be specific. Vague goals produce vague strategies.',
    timeline_label:  'Timeline',
    timeline_1m:     '1 month',
    timeline_3m:     '3 months',
    timeline_6m:     '6 months',
    timeline_1y:     '1 year',
    audience_label:  'Who are you trying to reach?',
    generating:      'Building your strategy...',
    generating_sub:  'This is worth the wait.',
    pillars_label:   'Strategic pillars',
    actions_label:   'Recommended actions',
    priority_high:   'High priority',
    priority_med:    'Medium',
    priority_low:    'When ready',
    export:          'Export strategy',
    refine:          'Refine this',
    empty:           'No strategy built yet.',
    empty_sub:       'A clear direction changes everything.',
  },
  ar: {
    heading:         'الاستراتيجية',
    subheading:      '.استراتيجيتك، مبنية بدقة. مو بسرعة',
    new_btn:         'ابنِ استراتيجية جديدة',
    template_label:  'ابدأ من قالب',
    custom_label:    'ابنِ من الصفر',
    goal_label:      'ايش تبي تحقق؟',
    goal_hint:       '.كن محدداً. الأهداف الضبابية تنتج استراتيجيات ضبابية',
    timeline_label:  'المدة الزمنية',
    timeline_1m:     'شهر',
    timeline_3m:     '3 أشهر',
    timeline_6m:     '6 أشهر',
    timeline_1y:     'سنة',
    audience_label:  'مين تحاول توصّل له؟',
    generating:      '...Nexa تبني استراتيجيتك',
    generating_sub:  '.الانتظار يستحق',
    pillars_label:   'الركائز الاستراتيجية',
    actions_label:   'الخطوات الموصى بها',
    priority_high:   'أولوية عالية',
    priority_med:    'متوسطة',
    priority_low:    'عند الاستعداد',
    export:          'صدّر الاستراتيجية',
    refine:          'صقّل هذا',
    empty:           '.ما انبنت استراتيجية بعد',
    empty_sub:       '.الاتجاه الواضح يغيّر كل شيء',
  },
}

// ── AUTOMATE (Studio copy keys also live here) ────────────────────────────────
export const automate = {
  en: {
    heading:          'Automate',
    subheading:       "Content that actually sounds like you. Generated, not written by committee.",
    type_caption:     'Caption',
    type_thread:      'Thread',
    type_email:       'Email',
    type_blog:        'Blog post',
    type_ad:          'Ad copy',
    type_bio:         'Brand bio',
    type_tagline:     'Tagline',
    type_script:      'Script',
    tone_bold:        'Bold',
    tone_calm:        'Calm',
    tone_warm:        'Warm',
    tone_sharp:       'Sharp',
    tone_poetic:      'Poetic',
    platform_ig:      'Instagram',
    platform_li:      'LinkedIn',
    platform_tw:      'X / Twitter',
    platform_email:   'Email',
    platform_web:     'Website',
    generating:       'Writing...',
    regenerate:       'Try again',
    copy_btn:         'Copy',
    copied:           'Copied',
    save_btn:         'Save',
    saved:            'Saved',
    refine_btn:       'Refine',
    topic_label:      "What's this about?",
    topic_hint:       "Give me a direction. I'll find the words.",
    empty:            'Nothing generated yet.',
    empty_sub:        "Tell me what you need. I'll write it.",
    history_label:    'Recent generations',
    words_label:      'words',
  },
  ar: {
    heading:          'الأتمتة',
    subheading:       '.محتوى يُشبهك فعلاً. مُولَّد، مو مكتوب بالتصويت',
    type_caption:     'كابشن',
    type_thread:      'ثريد',
    type_email:       'إيميل',
    type_blog:        'مقال',
    type_ad:          'نص إعلاني',
    type_bio:         'بايو البراند',
    type_tagline:     'تاغلاين',
    type_script:      'سكريبت',
    tone_bold:        'جريء',
    tone_calm:        'هادئ',
    tone_warm:        'دافئ',
    tone_sharp:       'حاد',
    tone_poetic:      'شاعري',
    platform_ig:      'إنستغرام',
    platform_li:      'لينكدإن',
    platform_tw:      'إكس',
    platform_email:   'الإيميل',
    platform_web:     'الموقع',
    generating:       '...Nexa تكتب',
    regenerate:       'جرّب مرة ثانية',
    copy_btn:         'نسخ',
    copied:           'تم النسخ',
    save_btn:         'حفظ',
    saved:            'تم الحفظ',
    refine_btn:       'صقّل',
    topic_label:      'عمَّ يتحدث المحتوى؟',
    topic_hint:       '.أعطني اتجاهاً. Nexa راح تلاقي الكلمات',
    empty:            '.ما تولّد شيء بعد',
    empty_sub:        '.قل لي ايش تحتاج. Nexa راح تكتبه',
    history_label:    'آخر ما ولّدته Nexa',
    words_label:      'كلمة',
  },
}

// ── STUDIO ───────────────────────────────────────────────────────────────────
export const studio = {
  en: {
    heading:          'Studio',
    subheading:       'Create. Refine. Publish. All in one place.',
    new_post:         'New post',
    new_image:        'Generate image',
    new_video:        'Generate video',
    new_voice:        'Generate voice',
    draft_label:      'Drafts',
    ready_label:      'Ready',
    published_label:  'Published',
    scheduled_label:  'Scheduled',
    all_label:        'All',
    edit_btn:         'Edit',
    publish_btn:      'Publish now',
    schedule_btn:     'Schedule',
    delete_btn:       'Delete',
    duplicate_btn:    'Duplicate',
    refine_btn:       'Refine with AI',
    copy_btn:         'Copy text',
    download_btn:     'Download',
    platform_label:   'Platform',
    type_label:       'Type',
    tone_label:       'Tone',
    generate_btn:     'Generate',
    generating:       'Creating...',
    empty_drafts:     'No drafts yet.',
    empty_sub:        'Your creations will appear here.',
    char_count:       'characters',
    word_count:       'words',
    voice_match:      'Voice match',
    on_brand:         'On brand',
    off_brand:        'Off brand',
  },
  ar: {
    heading:          'الاستوديو',
    subheading:       '.أنشئ. صقّل. انشر. كل شيء في مكان وحيد',
    new_post:         'منشور جديد',
    new_image:        'ولّد صورة',
    new_video:        'ولّد فيديو',
    new_voice:        'ولّد صوت',
    draft_label:      'المسودات',
    ready_label:      'جاهز',
    published_label:  'منشور',
    scheduled_label:  'مجدوَل',
    all_label:        'الكل',
    edit_btn:         'عدّل',
    publish_btn:      'انشر الحين',
    schedule_btn:     'جدوِل',
    delete_btn:       'احذف',
    duplicate_btn:    'كرّر',
    refine_btn:       'صقّل بالذكاء',
    copy_btn:         'انسخ النص',
    download_btn:     'نزّل',
    platform_label:   'المنصة',
    type_label:       'النوع',
    tone_label:       'النبرة',
    generate_btn:     'ولّد',
    generating:       '...Nexa تُبدع',
    empty_drafts:     '.ما في مسودات بعد',
    empty_sub:        '.إبداعاتك راح تظهر هنا',
    char_count:       'حرف',
    word_count:       'كلمة',
    voice_match:      'تطابق النبرة',
    on_brand:         'على النبرة',
    off_brand:        'خارج النبرة',
  },
}

// ── SCHEDULE ─────────────────────────────────────────────────────────────────
export const schedule = {
  en: {
    heading:         'Schedule',
    subheading:      'Your content calendar. Posts go live when they should.',
    month_view:      'Month',
    week_view:       'Week',
    list_view:       'List',
    today_btn:       'Today',
    add_post:        'Add post',
    no_posts:        'Nothing scheduled.',
    no_posts_sub:    'Schedule your first post from Studio.',
    scheduled_for:   'Scheduled for',
    publish_at:      'Publish at',
    platforms:       'Platforms',
    best_time:       'Best time',
    remove_btn:      'Remove',
    edit_btn:        'Edit',
    reschedule_btn:  'Reschedule',
    publish_now:     'Publish now',
    draft_badge:     'Draft',
    ready_badge:     'Ready',
    failed_badge:    'Failed',
  },
  ar: {
    heading:         'الجدول',
    subheading:      '.تقويم المحتوى. كل منشور ينزل في وقته الصح',
    month_view:      'شهر',
    week_view:       'أسبوع',
    list_view:       'قائمة',
    today_btn:       'اليوم',
    add_post:        'أضف منشور',
    no_posts:        '.ما في شيء مجدوَل',
    no_posts_sub:    '.جدوِل أول منشور من الاستوديو',
    scheduled_for:   'مجدوَل في',
    publish_at:      'ينشر في',
    platforms:       'المنصات',
    best_time:       'الوقت الأنسب',
    remove_btn:      'احذف',
    edit_btn:        'عدّل',
    reschedule_btn:  'أعد الجدولة',
    publish_now:     'انشر الحين',
    draft_badge:     'مسودة',
    ready_badge:     'جاهز',
    failed_badge:    'فشل',
  },
}

// ── AMPLIFY ──────────────────────────────────────────────────────────────────
export const amplify = {
  en: {
    heading:         'Amplify',
    subheading:      'Turn your best content into paid reach.',
    connect_meta:    'Connect Meta Ads',
    connect_sub:     'Link your Facebook & Instagram ad account to start.',
    boost_btn:       'Boost this post',
    create_ad:       'Create ad',
    budget_label:    'Daily budget',
    duration_label:  'Duration',
    audience_label:  'Target audience',
    objective_label: 'Objective',
    reach_label:     'Est. reach',
    spend_label:     'Total spend',
    status_active:   'Active',
    status_paused:   'Paused',
    status_ended:    'Ended',
    pause_btn:       'Pause',
    resume_btn:      'Resume',
    results_label:   'Results',
    cpm_label:       'CPM',
    ctr_label:       'CTR',
    empty:           'No active campaigns.',
    empty_sub:       'Boost your best content to reach more people.',
    connect_btn:     'Connect',
  },
  ar: {
    heading:         'Amplify',
    subheading:      '.حوّل أفضل محتواك إلى وصول مدفوع',
    connect_meta:    'وصّل Meta Ads',
    connect_sub:     '.ربط حساب إعلانات فيسبوك وإنستغرام للبدء',
    boost_btn:       'عزّز هذا المنشور',
    create_ad:       'أنشئ إعلان',
    budget_label:    'الميزانية اليومية',
    duration_label:  'المدة',
    audience_label:  'الجمهور المستهدف',
    objective_label: 'الهدف',
    reach_label:     'الوصول المتوقع',
    spend_label:     'الإنفاق الكلي',
    status_active:   'نشط',
    status_paused:   'موقوف',
    status_ended:    'منتهي',
    pause_btn:       'وقّف',
    resume_btn:      'استأنف',
    results_label:   'النتائج',
    cpm_label:       'تكلفة الألف',
    ctr_label:       'نسبة النقر',
    empty:           '.ما في حملات نشطة',
    empty_sub:       '.عزّز أفضل محتواك للوصول لجمهور أوسع',
    connect_btn:     'وصّل',
  },
}

// ── INTEGRATIONS ─────────────────────────────────────────────────────────────
export const integrations = {
  en: {
    heading:         'Integrations',
    subheading:      'Connect the tools you already use.',
    connected:       'Connected',
    connect_btn:     'Connect',
    disconnect_btn:  'Disconnect',
    reconnect_btn:   'Reconnect',
    last_sync:       'Last synced',
    status_ok:       'Active',
    status_error:    'Error',
    social_section:  'Social Platforms',
    email_section:   'Email Providers',
    other_section:   'Other Tools',
    available_badge: 'Available',
    empty:           'No integrations yet.',
    empty_sub:       'Connect your platforms to start publishing.',
  },
  ar: {
    heading:         'الاتصالات',
    subheading:      '.وصّل الأدوات اللي تستخدمها أصلاً',
    connected:       'متصل',
    connect_btn:     'وصّل',
    disconnect_btn:  'افصل',
    reconnect_btn:   'أعد الاتصال',
    last_sync:       'آخر مزامنة',
    status_ok:       'نشط',
    status_error:    'خطأ',
    social_section:  'المنصات الاجتماعية',
    email_section:   'مزودو الإيميل',
    other_section:   'أدوات أخرى',
    available_badge: 'متاح',
    empty:           '.ما في اتصالات بعد',
    empty_sub:       '.وصّل منصاتك للبدء بالنشر',
  },
}

// ── AGENCY ───────────────────────────────────────────────────────────────────
export const agency = {
  en: {
    heading:           'Agency',
    subheading:        'Your clients. Your control. One dashboard.',
    add_client:        'Add client',
    invite_client:     'Invite client',
    clients_label:     'Clients',
    active_label:      'Active',
    mrr_label:         'MRR',
    retainer_label:    'Retainer',
    switch_btn:        'Switch to workspace',
    view_btn:          'View details',
    remove_btn:        'Remove client',
    empty:             'No clients yet.',
    empty_sub:         'Add your first client to get started.',
    invite_sent:       'Invitation sent.',
    status_active:     'Active',
    status_paused:     'Paused',
    billing_label:     'Billing',
    notes_label:       'Notes',
    email_placeholder: 'client@email.com',
    sending:           'Sending...',
  },
  ar: {
    heading:           'الوكالة',
    subheading:        '.عملاؤك. تحكّمك. لوحة وحيدة',
    add_client:        'أضف عميل',
    invite_client:     'ادعو عميل',
    clients_label:     'العملاء',
    active_label:      'نشط',
    mrr_label:         'الإيراد الشهري',
    retainer_label:    'الاشتراك الثابت',
    switch_btn:        'انتقل للمساحة',
    view_btn:          'شوف التفاصيل',
    remove_btn:        'احذف العميل',
    empty:             '.ما في عملاء بعد',
    empty_sub:         '.أضف أول عميل وابدأ',
    invite_sent:       '.تم إرسال الدعوة',
    status_active:     'نشط',
    status_paused:     'موقوف',
    billing_label:     'الفوترة',
    notes_label:       'ملاحظات',
    email_placeholder: 'إيميل العميل...',
    sending:           '...جارٍ الإرسال',
  },
}

// ── SETTINGS ─────────────────────────────────────────────────────────────────
export const settings = {
  en: {
    heading:           'Settings',
    subheading:        'Your workspace. Your rules.',
    section_account:   'Account',
    section_brand:     'Brand profile',
    section_billing:   'Billing',
    section_language:  'Language',
    section_notif:     'Notifications',
    section_api:       'API access',
    section_danger:    'Danger zone',
    name_label:        'Full name',
    email_label:       'Email address',
    avatar_label:      'Profile photo',
    avatar_btn:        'Change photo',
    password_label:    'Password',
    password_btn:      'Change password',
    brand_name:        'Brand name',
    brand_industry:    'Industry',
    brand_tone:        'Default tone',
    brand_audience:    'Target audience',
    plan_label:        'Current plan',
    plan_free:         'Free',
    plan_pro:          'Pro',
    plan_agency:       'Agency',
    upgrade_btn:       'Upgrade plan',
    billing_btn:       'Manage billing',
    lang_label:        'Interface language',
    lang_en:           'English',
    lang_ar:           'العربية',
    notif_email:       'Email notifications',
    notif_product:     'Product updates',
    notif_insights:    'New insight alerts',
    api_key_label:     'API key',
    api_copy:          'Copy key',
    api_regen:         'Regenerate',
    api_warning:       'Keep this private. Treat it like a password.',
    delete_account:    'Delete account',
    delete_warning:    'This is permanent. There is no undo.',
    save_btn:          'Save changes',
    saved_msg:         'Saved.',
    cancel_btn:        'Cancel',
  },
  ar: {
    heading:           'الإعدادات',
    subheading:        '.مساحتك. قواعدك',
    section_account:   'الحساب',
    section_brand:     'ملف البراند',
    section_billing:   'الفوترة',
    section_language:  'اللغة',
    section_notif:     'الإشعارات',
    section_api:       'الوصول لـ API',
    section_danger:    'المنطقة الخطرة',
    name_label:        'الاسم الكامل',
    email_label:       'الإيميل',
    avatar_label:      'صورة الحساب',
    avatar_btn:        'غيّر الصورة',
    password_label:    'كلمة السر',
    password_btn:      'غيّر كلمة السر',
    brand_name:        'اسم البراند',
    brand_industry:    'القطاع',
    brand_tone:        'النبرة الافتراضية',
    brand_audience:    'الجمهور المستهدف',
    plan_label:        'الخطة الحالية',
    plan_free:         'مجاني',
    plan_pro:          'Pro',
    plan_agency:       'Agency',
    upgrade_btn:       'طوّر الخطة',
    billing_btn:       'أدر الفوترة',
    lang_label:        'لغة الواجهة',
    lang_en:           'English',
    lang_ar:           'العربية',
    notif_email:       'إشعارات الإيميل',
    notif_product:     'تحديثات المنتج',
    notif_insights:    'تنبيهات الإنسايتس الجديدة',
    api_key_label:     'مفتاح API',
    api_copy:          'انسخ المفتاح',
    api_regen:         'أعد التوليد',
    api_warning:       '.خلّه سراً. عامله مثل كلمة السر',
    delete_account:    'احذف الحساب',
    delete_warning:    '.هذا نهائي. ما في تراجع',
    save_btn:          'احفظ التغييرات',
    saved_msg:         '.تم',
    cancel_btn:        'إلغاء',
  },
}

// ── ONBOARDING ───────────────────────────────────────────────────────────────
export const onboarding = {
  en: {
    step1_heading:  "Let's build your brand brain.",
    step1_sub:      'A few questions. Then we get to work.',
    step2_heading:  'Tell me about your brand.',
    step2_sub:      "Don't overthink it. You can refine later.",
    step3_heading:  'Who are you talking to?',
    step3_sub:      'The clearer the picture, the sharper the output.',
    step4_heading:  'What does your brand sound like?',
    step4_sub:      'Pick the words that feel right.',
    step5_heading:  'Almost there.',
    step5_sub:      'Upload anything that represents your brand — optional, but powerful.',
    finish_btn:     "Let's go",
    skip_btn:       'Skip for now',
    next_btn:       'Next',
    back_btn:       'Back',
    progress:       'Step',
    of:             'of',
    brand_label:    'Brand name',
    industry_label: 'Industry',
    desc_label:     'What does your brand do?',
    audience_label: 'Who is your ideal audience?',
    voice_label:    'Brand voice',
    saving:         'Saving...',
  },
  ar: {
    step1_heading:  '.يلا نبني Brand Brain براندك',
    step1_sub:      '.بعض الأسئلة. ثم ننطلق',
    step2_heading:  '.حدّثني عن براندك',
    step2_sub:      '.ما تحتاج تفكّر كثير. تقدر تعدّل لاحقاً',
    step3_heading:  'مين تحاول توصّله؟',
    step3_sub:      '.كلما كانت الصورة أوضح، كان الناتج أحدّ',
    step4_heading:  'كيف يبدو براندك؟',
    step4_sub:      '.اختر الكلمات اللي تحس أنها تمثّلك',
    step5_heading:  '.ما تبقى شيء',
    step5_sub:      '.ارفع ما يُعبّر عن براندك — اختياري، لكنه قوي',
    finish_btn:     'يلا نبدأ',
    skip_btn:       'تخطّ الحين',
    next_btn:       'التالي',
    back_btn:       'رجوع',
    progress:       'خطوة',
    of:             'من',
    brand_label:    'اسم البراند',
    industry_label: 'القطاع',
    desc_label:     'ايش يسوّي براندك؟',
    audience_label: 'مين هو جمهورك المثالي؟',
    voice_label:    'صوت البراند',
    saving:         '...يحفظ',
  },
}

// ── AUTH ─────────────────────────────────────────────────────────────────────
export const auth = {
  en: {
    login_heading:        'Welcome back.',
    login_sub:            'Pick up where you left off.',
    signup_heading:       'Start building.',
    signup_sub:           'Your brand intelligence, finally.',
    email_label:          'Email',
    email_placeholder:    'you@example.com',
    password_label:       'Password',
    password_placeholder: '••••••••',
    name_label:           'Full name',
    name_placeholder:     'Your name',
    login_btn:            'Sign in',
    signup_btn:           'Create account',
    forgot_password:      'Forgot password?',
    no_account:           "Don't have an account?",
    have_account:         'Already have an account?',
    sign_up_link:         'Sign up',
    sign_in_link:         'Sign in',
    terms_agree:          'By signing up, you agree to our',
    terms_link:           'Terms of Service',
    privacy_link:         'Privacy Policy',
    reset_heading:        'Reset your password.',
    reset_sub:            "We'll send a link to your email.",
    reset_btn:            'Send reset link',
    reset_sent:           'Check your email.',
    back_to_login:        'Back to sign in',
    signing_in:           'Signing in...',
    creating:             'Creating account...',
    free_trial_badge:     '150 free credits — no credit card',
    error_invalid:        'Invalid email or password.',
    error_signup:         'Could not create account. Try again.',
  },
  ar: {
    login_heading:        '.أهلاً بعودتك',
    login_sub:            '.أكمل من حيث توقفت',
    signup_heading:       '.ابدأ البناء',
    signup_sub:           '.ذكاء براندك، أخيراً',
    email_label:          'الإيميل',
    email_placeholder:    'بريدك@مثال.com',
    password_label:       'كلمة السر',
    password_placeholder: '••••••••',
    name_label:           'الاسم الكامل',
    name_placeholder:     'اسمك',
    login_btn:            'سجّل الدخول',
    signup_btn:           'أنشئ حساب',
    forgot_password:      'نسيت كلمة السر؟',
    no_account:           'ما عندك حساب؟',
    have_account:         'عندك حساب بعد؟',
    sign_up_link:         'سجّل',
    sign_in_link:         'ادخل',
    terms_agree:          'بالتسجيل، أنت توافق على',
    terms_link:           'شروط الخدمة',
    privacy_link:         'سياسة الخصوصية',
    reset_heading:        '.إعادة تعيين كلمة السر',
    reset_sub:            '.بنرسل لك رابط على إيميلك',
    reset_btn:            'أرسل رابط الإعادة',
    reset_sent:           '.راجع إيميلك',
    back_to_login:        'ارجع لتسجيل الدخول',
    signing_in:           '...جارٍ التحقق',
    creating:             '...جارٍ الإنشاء',
    free_trial_badge:     '150 رصيد مجاناً — بدون بطاقة',
    error_invalid:        '.الإيميل أو كلمة السر غلط',
    error_signup:         '.ما قدرنا نسجّلك. جرّب مرة ثانية',
  },
}

// ── CHAT ─────────────────────────────────────────────────────────────────────
export const chat = {
  en: {
    placeholder:      'Ask anything about your brand...',
    send:             'Send',
    thinking:         'Thinking...',
    error:            'Something went wrong. Try again.',
    empty_heading:    'Ask me anything.',
    empty_sub:        "I know your brand. Let's talk about it.",
    suggestion_1:     'What does my brand sound like?',
    suggestion_2:     'Where am I inconsistent?',
    suggestion_3:     'Who is my ideal customer?',
    suggestion_4:     'What should I post this week?',
    copy_msg:         'Copy',
    regenerate_msg:   'Regenerate',
    clear:            'Clear chat',
    online:           'knows your brand',
    initialMessage:   'Your brand intelligence is online. What are we creating today?',
  },
  ar: {
    placeholder:      '...اسأل Nexa أي شيء عن براندك',
    send:             'أرسل',
    thinking:         '...Nexa تفكّر',
    error:            '.صار خطأ. جرّب مرة ثانية',
    empty_heading:    '.اسألني أي شيء',
    empty_sub:        '.أعرف براندك. خلنا نتكلم عنه',
    suggestion_1:     'كيف يبدو براندي؟',
    suggestion_2:     'وين مو متسق؟',
    suggestion_3:     'مين عميلي المثالي؟',
    suggestion_4:     'ايش أنشر هذا الأسبوع؟',
    copy_msg:         'انسخ',
    regenerate_msg:   'أعد التوليد',
    clear:            'امسح المحادثة',
    online:           'تعرف براندك',
    initialMessage:   '.ذكاء براندك جاهز. ايش نُبدع اليوم؟',
  },
}

// ── TOPBAR ───────────────────────────────────────────────────────────────────
export const topbar = {
  en: {
    search:         'Jump to anywhere…',
    notifications:  'Notifications',
    allCaughtUp:    "You're all caught up.",
    newBadge:       'new',
    enterToSend:    'Enter to send · Shift+Enter for new line',
    readingFile:    'Reading file…',
    messageNexa:    'Message Nexa…',
    topUp:          'Top up credits',
    creditsLeft:    'credits remaining',
    creditCosts:    'Credit costs',
    oneTime:        'One-time purchase · No subscription · Credits never expire',
    myWorkspace:    'My workspace',
    profile:        'Profile',
    workspace:      'Workspace',
    billing:        'Billing',
    signOut:        'Sign out',
    trialExpired:   '⚠ Trial expired',
    trialDays:      'Trial · {n}d left',
  },
  ar: {
    search:         '...اذهب لأي مكان',
    notifications:  'الإشعارات',
    allCaughtUp:    '.كل شيء واضح عندك',
    newBadge:       'جديد',
    enterToSend:    'Enter للإرسال · Shift+Enter لسطر جديد',
    readingFile:    '...Nexa تقرأ الملف',
    messageNexa:    '...راسل Nexa',
    topUp:          'اشحن الرصيد',
    creditsLeft:    'رصيد متبقٍ',
    creditCosts:    'تكلفة الرصيد',
    oneTime:        'شراء لمرة وحيدة · بدون اشتراك · الرصيد ما ينتهي',
    myWorkspace:    'مساحتي',
    profile:        'الحساب الشخصي',
    workspace:      'مساحة العمل',
    billing:        'الفوترة',
    signOut:        'تسجيل الخروج',
    trialExpired:   '⚠ انتهت التجربة',
    trialDays:      'تجربة · {n} أيام',
  },
}

// ── STATES & ERRORS ──────────────────────────────────────────────────────────
export const states = {
  en: {
    loading:         'Loading...',
    saving:          'Saving...',
    error_generic:   'Something went wrong.',
    error_network:   'Check your connection.',
    error_auth:      'Session expired. Please log in again.',
    error_limit:     "You've reached your plan limit.",
    upgrade_prompt:  'Upgrade to continue.',
    success_saved:   'Saved.',
    success_copied:  'Copied.',
    success_sent:    'Sent.',
    confirm_delete:  "Are you sure? This can't be undone.",
    confirm_yes:     'Yes, delete',
    confirm_no:      'Cancel',
    empty_generic:   'Nothing here yet.',
    coming_soon:     'Coming soon.',
  },
  ar: {
    loading:         '...يحمّل',
    saving:          '...يحفظ',
    error_generic:   '.صار خطأ',
    error_network:   '.تحقق من اتصالك',
    error_auth:      '.انتهت الجلسة. سجّل دخولك مرة ثانية',
    error_limit:     '.وصلت لحد خطتك',
    upgrade_prompt:  '.طوّر خطتك للمتابعة',
    success_saved:   '.تم',
    success_copied:  '.تم النسخ',
    success_sent:    '.تم الإرسال',
    confirm_delete:  'متأكد؟ ما في تراجع.',
    confirm_yes:     'نعم، احذف',
    confirm_no:      'إلغاء',
    empty_generic:   '.ما في شيء هنا بعد',
    coming_soon:     '.قريباً',
  },
}

// ── AGENTS ───────────────────────────────────────────────────────────────────
export const agents = {
  en: [
    { id: 'content',    name: 'Content Agent',    desc: 'Full week of brand posts'           },
    { id: 'timing',     name: 'Timing Agent',     desc: 'Optimal windows for your audience'  },
    { id: 'insights',   name: 'Insights Agent',   desc: 'Weekly digest with next steps'      },
    { id: 'engagement', name: 'Engage Agent',     desc: 'Replies in your exact brand voice'  },
  ],
  ar: [
    { id: 'content',    name: 'وكيل المحتوى',    desc: 'أسبوع كامل من منشورات براندك'      },
    { id: 'timing',     name: 'وكيل التوقيت',    desc: 'أفضل أوقات النشر لجمهورك'          },
    { id: 'insights',   name: 'وكيل الإنسايتس',  desc: 'ملخص أسبوعي مع الخطوات الجاية'    },
    { id: 'engagement', name: 'وكيل التفاعل',    desc: 'ردود بنبرة براندك تحديداً'         },
  ],
}

// ── STATUS LABELS ─────────────────────────────────────────────────────────────
export const statusLabels: Record<string, { en: string; ar: string }> = {
  on_fire:       { en: 'On Fire',     ar: 'في أوجه'     },
  building:      { en: 'Building',    ar: 'في الطريق'   },
  needs_push:    { en: 'Needs Push',  ar: 'يحتاج دفعة'  },
  just_starting: { en: 'Starting Up', ar: 'في البداية'  },
}

// ── QUICK CHAT SUGGESTIONS ───────────────────────────────────────────────────
export const quickSuggestions = {
  en: ['Write a post', 'Build strategy', 'Analyze brand', 'Content ideas'],
  ar: ['اكتب منشور', 'بناء استراتيجية', 'حلّل البراند', 'أفكار محتوى'],
}

// ── PRICING PAGE ─────────────────────────────────────────────────────────────
export const pricing = {
  en: {
    eyebrow:          'Pricing',
    heading_line1:    'Simple.',
    heading_line2:    'Honest.',
    heading_line3:    'Scalable.',
    subheading:       'Start with 150 free credits. No credit card required. Upgrade when you are ready.',
    guarantee:        'All plans include a 7-day money-back guarantee · Cancel anytime',
    popular_badge:    'POPULAR',
    free_trial_badge: '150 CR FREE',
    per_month:        '/mo',
    get_started:      'Get started',
    choose_plan:      'Choose plan',
    credit_costs:     'Credit costs per action',
    chat_free:        'Chat, strategy generation, and content scheduling are always free.',
    faq_heading:      'Still have questions?',
    sign_in:          'Sign in',
    start_free:       'Start free →',
    back_to_nexa:     '← Back to Nexa',
    footer_copy:      '© 2026 Nexa · hello@nexaa.cc',
    terms:            'Terms',
    privacy:          'Privacy',
  },
  ar: {
    eyebrow:          'الأسعار',
    heading_line1:    'بسيط.',
    heading_line2:    'صريح.',
    heading_line3:    'ينمو معك.',
    subheading:       '.ابدأ بـ 150 رصيداً مجاناً. بدون بطاقة. طوّر خطتك متى جهزت',
    guarantee:        'كل الخطط فيها ضمان استرداد 7 أيام · إلغاء وقت ما تبي',
    popular_badge:    'الأكثر طلباً',
    free_trial_badge: '150 رصيد مجاناً',
    per_month:        '/شهر',
    get_started:      'ابدأ الحين',
    choose_plan:      'اختر الخطة',
    credit_costs:     'تكلفة الرصيد لكل إجراء',
    chat_free:        '.المحادثة وبناء الاستراتيجية والجدولة مجانية دائماً',
    faq_heading:      'عندك أسئلة؟',
    sign_in:          'سجّل الدخول',
    start_free:       'ابدأ مجاناً ←',
    back_to_nexa:     'Nexa ← ارجع لـ',
    footer_copy:      '© 2026 Nexa · hello@nexaa.cc',
    terms:            'الشروط',
    privacy:          'الخصوصية',
  },
}

// ── MORNING BRIEF ─────────────────────────────────────────────────────────────
export const brief = {
  en: {
    heading:        "Today's Brief",
    subheading:     "What matters this morning.",
    generated_at:   'Generated at',
    top_angle:      'Top angle',
    platform_rec:   'Post this on',
    refresh_btn:    'Refresh brief',
    loading:        'Preparing your brief...',
    empty:          'No brief yet.',
    empty_sub:      'Come back tomorrow morning.',
    nexa_read:      "Nexa's read",
    content_idea:   'Content idea',
  },
  ar: {
    heading:        'ملخص اليوم',
    subheading:     '.أهم ما عليك الصبح',
    generated_at:   'تم الإنشاء في',
    top_angle:      'أفضل زاوية',
    platform_rec:   'انشر على',
    refresh_btn:    'جدّد الملخص',
    loading:        '...Nexa تُعدّ ملخصك',
    empty:          '.ما في ملخص بعد',
    empty_sub:      '.ارجع بكرة الصبح',
    nexa_read:      'ما شافته Nexa',
    content_idea:   'فكرة محتوى',
  },
}

// ── MASTER HELPER ────────────────────────────────────────────────────────────
export function t(
  section: Record<string, Record<string, string>>,
  lang: Lang
): Record<string, string> {
  return section[lang] ?? section['en']
}
