-- ── Nexa Intelligence Layer Migration ──────────────────────────────────────

-- Add client stage tracking to workspaces
ALTER TABLE public.workspaces
  ADD COLUMN IF NOT EXISTS client_stage text
  CHECK (client_stage IN ('foundation','momentum','amplify','operate','dominate'))
  DEFAULT 'foundation';

-- Add weekly priorities cache (generated by intelligence engine cron)
ALTER TABLE public.workspaces
  ADD COLUMN IF NOT EXISTS weekly_priorities jsonb,
  ADD COLUMN IF NOT EXISTS weekly_priorities_ar jsonb,
  ADD COLUMN IF NOT EXISTS priorities_generated_at timestamptz;

-- Roadmap milestones table
CREATE TABLE IF NOT EXISTS public.roadmap_milestones (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id    uuid NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  stage           text NOT NULL,
  title           text NOT NULL,
  title_ar        text,
  description     text,
  target_metric   text,
  current_value   text,
  target_value    text,
  status          text DEFAULT 'active'
    CHECK (status IN ('active','completed','skipped')),
  due_date        date,
  completed_at    timestamptz,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_roadmap_workspace
  ON public.roadmap_milestones(workspace_id);

ALTER TABLE public.roadmap_milestones ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Members access roadmap"
  ON public.roadmap_milestones FOR ALL
  USING (EXISTS (
    SELECT 1 FROM workspace_members
    WHERE workspace_id = roadmap_milestones.workspace_id
    AND user_id = auth.uid()
  ));
